import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {bySlug,programs} from "../data";
import {LineIcon,ProgramFooter,ProgramHeader} from "../components";
export function generateStaticParams(){return programs.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=bySlug(slug);if(!p)return{};return{title:p.title+" | Fundación Tejiendo",description:p.summary,alternates:{canonical:"/programas/"+p.slug},openGraph:{title:p.title,description:p.tagline,type:"website"}}}
const stages=["Identificación","Caracterización","Diseño del acompañamiento","Intervención","Seguimiento","Evaluación y cierre"];
const allies=["Entidades territoriales y nacionales","Empresas y fundaciones empresariales","Universidades y cooperativas","Embajadas y agencias de cooperación","ONG e iglesias","Organizaciones comunitarias y donantes"];
const safeguards=["Debida diligencia","Uso responsable de recursos","Protección de datos y confidencialidad","Protección de población vulnerable","Prevención del abuso y el acoso","Prevención del fraude y la corrupción","Rendición de cuentas","Seguimiento y evaluación"];
export default async function ProgramDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=bySlug(slug);if(!p)notFound();const related=p.related.map(bySlug).filter(Boolean);return <><ProgramHeader/><main><section className="detail-hero" style={{"--accent":p.accent} as React.CSSProperties}><div className="detail-hero-inner"><div className="breadcrumbs"><Link href="/">Inicio</Link><span>/</span><Link href="/programas">Programas</Link><span>/</span><b>{p.title}</b></div><div className="detail-title"><LineIcon number={p.number}/><div><span>Programa institucional</span><h1>{p.title}</h1><p>{p.tagline}</p><div><a className="button" href="#participar">Quiero participar</a><a className="button button-ghost" href="#alianzas">Presentar una alianza</a></div></div></div></div></section>
<section className="section detail-intro"><div><span className="mini-kicker">El desafío</span><h2>Una respuesta integral, humana y técnicamente responsable.</h2></div><div><p>{p.problem}</p><p>{p.summary} Se relaciona con el objeto social de la Fundación al convertir redes de apoyo, conocimiento y cooperación en capacidades sostenibles.</p>{p.notice&&<aside>{p.notice}</aside>}</div></section>
<section className="objective-band"><div className="section"><span>Objetivo general</span><h2>{p.objective}</h2><div className="specific-objectives"><h3>Objetivos específicos</h3><ol>{p.objectives.map(x=><li key={x}>{x}</li>)}</ol></div></div></section>
<section className="section components-section"><div className="program-section-head"><span>Componentes del programa</span><h2>Capacidades que organizan la intervención</h2></div><div className="component-grid">{p.components.map((c,i)=><article key={c.title}><b>0{i+1}</b><h3>{c.title}</h3><p>{c.description}</p><dl><dt>Tipo de actividad</dt><dd>{c.activity}</dd><dt>Meta institucional</dt><dd>{c.result}</dd></dl></article>)}</div></section>
<section className="path-section"><div className="section"><div className="program-section-head light-head"><span>Ruta de acompañamiento</span><h2>Un proceso claro, verificable y centrado en la persona</h2></div><div className="detail-path">{stages.map((x,i)=><div key={x}><b>{String(i+1).padStart(2,"0")}</b><strong>{x}</strong></div>)}</div></div></section>
<section className="section services-pop"><div><span className="mini-kicker">Servicios y actividades</span><h2>Modalidades posibles de intervención</h2><ul className="check-list">{p.services.map(x=><li key={x}>✓ <span>{x}</span></li>)}</ul><p className="availability-note">Su ejecución dependerá de los proyectos, recursos, alianzas y convocatorias disponibles.</p></div><div><span className="mini-kicker">Población relacionada</span><h2>Enfoque diferencial</h2><div className="population-tags">{p.populations.map(x=><span key={x}>{x}</span>)}</div><p className="availability-note">Poblaciones potencialmente beneficiarias; esta identificación no afirma atención actual.</p></div></section>
<section className="allies-section" id="alianzas"><div className="section allies-grid"><div><span className="mini-kicker light-text">Cooperación y alianzas</span><h2>Sumamos capacidades para ampliar soluciones.</h2><p>Las alianzas combinan conocimiento, legitimidad territorial, recursos y seguimiento.</p><Link className="button button-white" href={"/#formulario"}>Construir una propuesta conjunta →</Link></div><div>{allies.map(x=><span key={x}>↗ {x}</span>)}</div></div></section>
<section className="section safeguards"><div><span className="mini-kicker">Transparencia y salvaguardas</span><h2>Protegemos a las personas, los recursos y el propósito.</h2></div><div className="safeguard-grid">{safeguards.map(x=><span key={x}>✓ {x}</span>)}</div></section>
<section className="indicator-section"><div className="section"><div className="program-section-head"><span>Indicadores institucionales sugeridos</span><h2>Medir para aprender y mejorar</h2><p>Son indicadores propuestos para futuros proyectos; no representan resultados alcanzados.</p></div><div className="indicator-grid">{p.indicators.map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div></div></section>
<section className="section related-section"><div className="program-section-head"><span>Programas relacionados</span><h2>Una respuesta conectada</h2></div><div className="related-grid">{related.map(r=>r&&<Link key={r.slug} href={"/programas/"+r.slug} style={{"--accent":r.accent} as React.CSSProperties}><LineIcon number={r.number}/><strong>{r.title}</strong><span>Conocer programa →</span></Link>)}</div></section>
<section className="participation-section" id="participar"><div className="section participation-grid"><div><span className="mini-kicker light-text">Participa</span><h2>Cada transformación comienza cuando conectamos una necesidad con una capacidad.</h2><p>Puedes solicitar orientación, postular una comunidad, ser voluntario, aportar o proponer una alianza.</p></div><form action="https://formsubmit.co/karinnalozz20@gmail.com" method="POST"><input type="hidden" name="_subject" value={"Solicitud sobre programa: "+p.title}/><input type="hidden" name="_template" value="table"/><input type="hidden" name="Programa consultado" value={p.title}/><input type="hidden" name="Página de origen" value={"/programas/"+p.slug}/><input className="form-honey" type="text" name="_honey" tabIndex={-1}/><div className="form-row"><label>Nombre<input name="Nombre" required/></label><label>Organización<input name="Organización"/></label></div><div className="form-row"><label>Correo<input type="email" name="email" required/></label><label>Teléfono opcional<input name="Teléfono"/></label></div><label>Tipo de participación<select name="Tipo de solicitud" defaultValue="" required><option value="" disabled>Selecciona</option><option>Solicitar orientación</option><option>Postular una comunidad</option><option>Ser voluntario</option><option>Realizar un aporte</option><option>Presentar una alianza</option><option>Financiar un proyecto</option><option>Aportar bienes, servicios o conocimiento</option></select></label><label>Mensaje<textarea name="Mensaje" rows={4} required/></label><label className="consent"><input type="checkbox" name="Autorización de tratamiento" value="Autorizada" required/><span>Autorizo el tratamiento de esta información para atender mi solicitud.</span></label><button className="button" type="submit">Enviar solicitud</button></form></div></section></main><ProgramFooter/></>}
