import type {Metadata} from "next";
import Link from "next/link";
import {JsonLd} from "../components/JsonLd";
import {ProgramFooter,ProgramHeader} from "../programas/components";
import {SITE_URL} from "../site";

export const metadata:Metadata={title:"Proyectos y evidencias",description:"Marco de publicación y verificación de proyectos sociales de la Fundación Tejiendo con Latidos de Esperanza.",alternates:{canonical:"/proyectos"}};
const evidence=["Problema y población definidos","Territorio y periodo verificables","Aliados y responsabilidades confirmados","Recursos y actividades documentados","Indicadores con fuente y fecha","Resultados diferenciados de metas"];
export default function Page(){const structured={"@context":"https://schema.org","@type":"CollectionPage",name:"Proyectos y evidencias",url:`${SITE_URL}/proyectos`,inLanguage:"es-CO",about:{"@id":`${SITE_URL}/#organization`}};return <><ProgramHeader/><main id="contenido"><header className="evidence-hero projects"><div><span>Impacto responsable</span><h1>Los proyectos se publican con evidencia, no con promesas</h1><p>La Fundación contará cada intervención cuando exista información validada sobre propósito, alcance, participantes, aliados, recursos y resultados.</p></div></header><section className="section evidence-grid"><div><span className="section-kicker">Estándar de publicación</span><h2>Qué debe demostrar cada ficha de proyecto</h2><p className="lead">Este control evita presentar metas futuras como resultados alcanzados o alianzas propuestas como acuerdos formalizados.</p></div><div className="evidence-checks">{evidence.map(item=><span key={item}>✓ {item}</span>)}</div></section><section className="section project-empty"><span>Registro público</span><h2>Las fichas verificadas se incorporarán en este espacio</h2><p>Aún no se publican proyectos ni cifras porque falta recibir y aprobar sus soportes institucionales. El repositorio ya contiene la plantilla que permitirá completar cada caso de forma consistente.</p><div><Link className="button" href="/alianzas">Presentar una alianza</Link><Link className="button button-ghost" href="/programas">Conocer los programas</Link></div></section></main><ProgramFooter/><JsonLd data={structured}/></>}
