import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {JsonLd} from "../../components/JsonLd";
import {ProgramFooter,ProgramHeader} from "../../programas/components";
import {SITE_URL} from "../../site";
import {resourceBySlug,resources} from "../data";

export function generateStaticParams(){return resources.map(resource=>({slug:resource.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const resource=resourceBySlug(slug);if(!resource)return{};return{title:resource.title,description:resource.summary,alternates:{canonical:`/recursos/${slug}`},openGraph:{title:resource.title,description:resource.summary,type:"article",url:`${SITE_URL}/recursos/${slug}`,publishedTime:resource.updated,modifiedTime:resource.updated}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const resource=resourceBySlug(slug);if(!resource)notFound();const structured={"@context":"https://schema.org","@type":"Article",headline:resource.title,description:resource.summary,datePublished:resource.updated,dateModified:resource.updated,inLanguage:"es-CO",author:{"@type":"Organization",name:"Equipo de contenidos de la Fundación"},publisher:{"@id":`${SITE_URL}/#organization`},mainEntityOfPage:`${SITE_URL}/recursos/${slug}`,about:resource.cluster};return <><ProgramHeader/><main id="contenido"><article className="resource-article"><header><Link href="/recursos">← Centro de conocimiento</Link><span>{resource.cluster} · {resource.readingTime}</span><h1>{resource.title}</h1><p>{resource.summary}</p><div className="resource-byline"><span><b>Autoría</b>Equipo de contenidos institucionales</span><span><b>Revisión</b>Jurídica e institucional</span><span><b>Actualización</b>24 de agosto de 2026</span></div></header><div className="resource-body"><p className="resource-intro">{resource.intro}</p>{resource.sections.map(section=><section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{section.steps&&<ul>{section.steps.map(step=><li key={step}>{step}</li>)}</ul>}</section>)}<aside className="resource-notice"><strong>Alcance de esta guía</strong><p>{resource.notice}</p></aside><section className="resource-sources"><h2>Fuentes oficiales consultadas</h2>{resource.sources.map(source=><a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a>)}</section><nav className="resource-next" aria-label="Siguientes pasos"><Link href={`/programas/${resource.programSlug}`}>Conocer el programa: {resource.programTitle}</Link><Link className="button" href="/solicitar-orientacion">Solicitar orientación</Link></nav></div></article></main><ProgramFooter/><JsonLd data={structured}/></>}
