import type {Metadata} from "next";
import Link from "next/link";
import {programs} from "./data";
import {LineIcon,ProgramFooter,ProgramHeader} from "./components";
export const metadata:Metadata={title:"Programas | Fundación Tejiendo con Latidos de Esperanza",description:"Conoce las nueve líneas de acción de la Fundación: protección, educación, inclusión productiva, vivienda, alimentación, acompañamiento psicosocial, respuesta humanitaria, cooperación y transparencia.",alternates:{canonical:"/programas"},openGraph:{title:"Programas que transforman realidades",description:"Nueve líneas integradas para proteger derechos, fortalecer capacidades y reconstruir tejido social.",type:"website"}};
const route=["Diagnóstico","Protección","Formación","Acompañamiento","Autonomía","Inclusión","Bienestar"];
const approaches=["Enfoque de derechos","Enfoque diferencial","Equidad de género","Participación comunitaria","Sostenibilidad","Transparencia","Protección de beneficiarios","Articulación institucional"];
export default function ProgramsPage(){return <><ProgramHeader/><main><section className="programs-hero"><div className="programs-hero-inner"><div><span className="program-eyebrow">Programas y líneas de acción</span><h1>Capacidades que se convierten en <em>transformación.</em></h1><p>Trabajamos mediante nueve líneas integradas para proteger derechos, fortalecer capacidades, promover autonomía y reconstruir el tejido social.</p><div className="program-buttons"><a className="button" href="#catalogo">Explorar los programas →</a><Link className="button button-ghost" href="/#participa">Presentar una oportunidad de cooperación</Link></div></div><div className="hero-program-stat"><strong>09</strong><span>Líneas articuladas</span><p>Una misma misión: acompañar a las personas con dignidad, capacidad técnica y transparencia.</p></div></div></section>
<section className="section intervention"><div className="program-section-head"><span>Nuestro modelo de intervención</span><h2>De la necesidad a una capacidad sostenible</h2><p>Esta ruta orienta el diseño institucional de los proyectos. No representa resultados ya ejecutados.</p></div><div className="route-flow">{route.map((x,i)=><div key={x}><b>{String(i+1).padStart(2,"0")}</b><strong>{x}</strong>{i<route.length-1&&<i>→</i>}</div>)}</div><span className="institutional-label">Modelo institucional de intervención</span></section>
<section className="catalog-section" id="catalogo"><div className="section"><div className="program-section-head light-head"><span>Explora nuestras líneas</span><h2>Nueve programas, una visión integral</h2><p>Cada línea responde a un desafío particular y se conecta con las demás.</p></div><div className="catalog-grid">{programs.map(p=><article key={p.slug} style={{"--accent":p.accent} as React.CSSProperties}><LineIcon number={p.number}/><h3>{p.title}</h3><p>{p.summary}</p><div className="population-mini">{p.populations.slice(0,2).map(x=><span key={x}>{x}</span>)}</div><a href={"/programas/"+p.slug} aria-label={"Conocer el programa "+p.title}>Conocer el programa <b aria-hidden="true">→</b></a></article>)}</div></div></section>
<section className="section approaches"><div className="program-section-head"><span>Enfoques transversales</span><h2>Principios presentes en cada intervención</h2></div><div className="approach-grid">{approaches.map((x,i)=><div key={x}><b>0{i+1}</b><strong>{x}</strong></div>)}</div></section>
<section className="program-callout"><div><span>Cooperación y acción colectiva</span><h2>Construyamos soluciones que dejen capacidad instalada en las comunidades.</h2><p>Convocamos a instituciones públicas, empresas, universidades, cooperantes, ONG, iglesias y donantes.</p><div><Link className="button button-white" href="/#participa">Ser aliado</Link><Link className="button outline-white" href="/#aportes">Financiar o aportar conocimiento</Link></div></div></section></main><ProgramFooter/></>}
